[lib]
crate-type = ["cdylib"]
path = "src/lib.rs"

[[bin]]
name = "spemath-cli"
path = "src/main.rs"

[package]
name = "spemath"
version = "0.1.0"
edition = "2024"

[dependencies]
log = "0.4"
env_logger = "0.11.8"
thiserror = "2.0.17"
wasm-bindgen = "0.2"
